#!/bin/bash
DOCKER_IMAGE="$(egrep -v '(^#|^\s*$|^\s*\t*#)' nifiVersion.txt)"
echo "Running Docker Image: $DOCKER_IMAGE"
docker run -d --platform linux/amd64 -p 8443:8443 -p 8080:8080 -p 8181:8181 $DOCKER_IMAGE


# NIFI_REMOTE_INPUT_SECURE=
# NIFI_WEB_HTTP_HOST=
# NIFI_WEB_HTTP_PORT=
# NIFI_WEB_HTTP_NETWORK_INTERFACE_DEFAULT=
# NIFI_WEB_HTTPS_HOST=
# NIFI_WEB_HTTPS_PORT=
# NIFI_SECURITY_KEYSTORE=
# NIFI_SECURITY_KEYSTORETYPE=
# NIFI_SECURITY_KEYSTOREPASSWD=
# NIFI_SECURITY_KEYPASSWD=
# NIFI_SECURITY_TRUSTSTORE=
# NIFI_SECURITY_TRUSTSTORETYPE=
# NIFI_SECURITY_TRUSTSTOREPASSWD=