global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'NiFi'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9092']